### ISSUE TITLE
Create a secure way to share the session ID on GitHub

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-GithubFeedbackForm#3]
Possibly: store it with a new random GUID in redis.

**Comment by BryceStevenWilley** [comment]
How exactly would we use the session ID once we have it? Is there something in the DA UI that lets us access it, or would we need to manually query the server DB itself?

Asking because an even easier solution would be to hash the session ID on the github issue. Then we just need an easy way to check that hash against existing sever session ids, which could be in the form of a dashboard tool if it should be through the UI, or a simple script if it's in the DB.

**Comment by nonprofittechy** [comment]
We can make a lookup tool for it in the dashboard. I'd be okay with putting hashed session id in a GitHub issue if we salt it, maybe with a unique value we store in the config.

**Comment by BryceStevenWilley** [comment]
Looking into this a bit more, I don't think storing the hash in the issue a good idea. [Salts don't protect against targeted attacks](https://cwe.mitre.org/data/definitions/760.html), and if all of these hashes are just out in public on GitHub, we don't know who might be targeted (especially if the attacker knows the interview is multi user and stores personal information (addresses, etc) ). My suggestion was to avoid the complexity of storing more information on the server, but the only safe way seems to be storing the salt on the server when adding the hash to the GitHub issue, which results in a much more complex situation than just storing a GUID with the session ID in secret.

It looks like I'll end up needing some salting / hash for the session ID just to pass it to the feedback interview through the URL, just so it's not in the URL plaintext, so I think the only thing that's changing here is storing the UUID in the issue instead of the hash.

IMO, it's also another mark against putting things directly on GitHub in the first place, but that's a separate discussion.

**Comment by nonprofittechy** [comment]
Yeah, it sounds like there's no secure way to store the session ID in the issue, even in a hashed form. We could go the other way and store the feedback in the database with a link to the Github issue, so only admins ever see it.

While the feedback link is a plain URL with URL parameters right now, we can change it so we pre-generate a session and store the variables in the background before giving the user a link with `interview_url_action()`, it would just be bit trickier to make that happen at the right time. Are you think about a history attack on the local machine? The URL parameters are not exposed to someone who isn't on the same machine or has MITMed the SSL connection.

**Comment by BryceStevenWilley** [comment]
I ended up implementing exactly that admin interview anyway, that seems like the best way.

> Are you think about a history attack on the local machine?

Kinda, less of an attack and malicious user on the same machine (maybe libraries?) or an over-the-shoulder glance, which you're right, probably isn't realistic, and doesn't really protect from the fact that they're likely able to log into the person's account if they have access to the machine anyway.

**Comment by BryceStevenWilley** [comment]
Fixed in #9, and it's pretty well wrapped up. Here's what the session ID review screen looks like (not sure I added that to the PR).
![Screenshot from 2022-07-20 10-56-40](https://user-images.githubusercontent.com/6252212/180014672-dffca05e-f676-4d4c-b522-026397713a43.png)



Closing as completed.
